name: gtsfm
channels:
  - menpo
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - autopep8
  - pylint
  - pytype
  - coverage
  - numpy
  - dask
  - pytest
  - pytorch
  - cudatoolkit=10.2
  - opencv=3.4.2
  - pip:
    - pydegensac



