name: gtsfm-v1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # python essentials
  - python=3.8
  - pip
  # formatting and dev environment
  - black
  - coverage
  - mypy
  - pylint
  - pytest
  # dask and related
  - dask
  - python-graphviz
  # core functionality and APIs
  - matplotlib>=3.3.3
  - networkx
  - numpy
  - pandas
  - pillow>=8.0.1
  - scikit-learn
  # 3rd party algorithms for different modules
  - cudatoolkit=10.2
  - opencv=4.5.0
  - pytorch
  - pip:
    # - gtsam==4.1.0
    - pydegensac



