_target_: gtsfm.loader.olsson_loader.OlssonLoader
folder: ${hydra:runtime.cwd}/tests/data/set1_lund_door
image_extension: "jpg"
use_gt_intrinsics: True
use_gt_extrinsics: True
max_frame_lookahead: 20
max_resolution: 760