# @package _global_
MultiViewOptimizer:
  _target_: gtsfm_cfgnode.MultiViewOptimizer
  submodule1: # SubModule1 name 
    param_str: mo_name1
    param_int: 5
    param_float: 5.0
    param_bool: true
  submodule2: # SubModule2 name 
    param_str: mo_name2
    param_int: 6
    param_float: 6.0
    param_bool: false

