# @package _global_
TwoViewEstimator:
  _target_: gtsfm_cfgnode.TwoViewEstimator
  submodule1: # SubModule1 name 
    param_str: te_name1
    param_int: 3
    param_float: 3.0
    param_bool: true
  submodule2: # SubModule2 name 
    param_str: te_name2
    param_int: 4
    param_float: 4.0
    param_bool: false
