# This is an example configuration file that helps authors to create their 
# own configuration files for their own experiments and settings.
# Please only follow the definition pattern in this file. Specific module or
# parameter names and values may be modified as desired. The parameters
# defined below are created only for the purpose of unit tests/examples.

SceneOptimizer: # Module name
  path: ~/gtsfm # this is the path to the module [str]
  enable_gpu: False # enable gpu or not [bool]
  image_path: [images1, images2, images3] # a list of path of input image folders

FeatureExtractor: # Module name 
  matching: # SubModule name
    num_features: 2000 # bla bla
    tol: 1e-3 # bla bla
    pyramid_scale: [1, 2, 4] # bla bla
  tracking: 
    num_features: 2000 # bla bla
    tol: 1e-3 # bla bla
    pyramid_scale: [1, 2, 4] # bla bla
  
TwoViewEstimator:
  min_measurements_per_track: 2 # bla bla

MultiViewOptimizer:
  bundleAdjuster:
    tol: 1e-3
