# This is an example configuration file that helps authors to create their 
# own configuration files for their own experiments and settings.
# Please only follow the definition pattern in this file. Specific module or
# parameter names and values may be modified as desired. The parameters
# defined below are created only for the purpose of unit tests/examples.

FeatureExtractor: # Module name 
  matching: # SubModule name
    num_features: 1000 # bla bla
    deep_feature: superpoint

TwoViewEstimator:
  mode_triangulation: ransac # bla bla

MultiViewOptimizer: # bla bla
  enable_vis: True