SceneOptimizer:
  param_str: name
  param_int: 0
  param_float: 0.0
  param_bool: true

FeatureExtractor:
  submodule1: # SubModule1 name 
    param_str: fe_name1
    param_int: 1
    param_float: 1.0
    param_bool: true
  submodule2: # SubModule2 name 
    param_str: fe_name2
    param_int: 2
    param_float: 2.0
    param_bool: false

TwoViewEstimator:
  _target_: gtsfm_cfgnode.TwoViewEstimator
  submodule1: # SubModule1 name 
    param_str: te_name1
    param_int: 3
    param_float: 3.0
    param_bool: true
  submodule2: # SubModule2 name 
    param_str: te_name2
    param_int: 4
    param_float: 4.0
    param_bool: false

MultiViewOptimizer:
  _target_: gtsfm_cfgnode.MultiViewOptimizer
  submodule1: # SubModule1 name 
    param_str: mo_name1
    param_int: 5
    param_float: 5.0
    param_bool: true
  submodule2: # SubModule2 name 
    param_str: mo_name2
    param_int: 6
    param_float: 6.0
    param_bool: false