name: Benchmark GTSFM on select datasets
on: [pull_request]
jobs:
  door-dataset-sift:
    name: Run GTSFM on the door dataset using SIFT front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    env:
      PYTHON_VERSION: 3.8

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: gtsfm-v1
          environment-file: environment_linux.yml
          python-version: 3.8
      - name: Environment setup
        run: |
          bash .github/scripts/setup.sh
          pip install hydra-core==1.1.0
          conda info
      - name: Execute SFM
        run: |
          python gtsfm/runner/run_scene_optimizer.py --config_name sift_front_end.yaml
      - name: Archive metrics
        uses: actions/upload-artifact@v2
        with:
          name: raw-metrics
          path: |
            result_metrics
