name: Python CI

# Run this workflow every time a new commit pushed to your repository
on: [pull_request, workflow_dispatch]

jobs:
  install-dependencies:
    name: Unit testing and evaluation
    runs-on: ubuntu-latest
    env: 
      PYTHON_VERSION: 3.8
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup conda env
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: gtsfm-v1
        environment-file: environment_linux.yml
        python-version: 3.8
    - name: Run installation script
      shell: bash -l {0}
      run: |
        bash .github/scripts/install_dependencies.sh
    - name: Run evaluation script
      shell: bash -l {0}
      run: |
        conda info --envs
        bash .github/scripts/run_eval.sh
    - name: Upload generated plots HTML
      uses: actions/upload-artifact@v2
      with:
        name: gtsfm-metrics-plots.html
        path: result_metrics/gtsfm_metrics_plots.html
    - name: Run unit tests
      shell: bash -l {0}
      run: |
        pip install pytest-cov
        conda info --envs
        bash .github/scripts/run_unit_tests.sh