name: Python CI

# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  run-unit-tests:

    name: Run all unit tests in code base
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.8

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: gtsfm-v1
        environment-file: environment_linux.yml
        python-version: 3.8
    - name: Environment setup
      shell: bash -l {0}
      run: |
        bash .github/scripts/setup.sh
        pip install pytest-cov
        pip install flake8
        pip install hydra-core==1.1.0
    - name: Flake check
      run: |
        flake8 --max-line-length 120 --ignore E201,E202,E203,E231,W291,W293,E303,W391,E402,W503,E731 gtsfm
    - name: Unit tests
      run: |
        pytest tests --cov gtsfm
        coverage report
    - name: React-Three-Fiber app tests
      run: |
        cd rtf_vis_tool && npm install && npm test a
        
